### ISSUE TITLE
Switch to RecyclerView

### ISSUE THREAD

**Issue by winterweird** [winterweird/jpractice#1]
Switch from ListView to RecyclerView in the activities under Word lists

## Task list
- [x] Switch from ListView to RecyclerView in NamedListsActivity
  - [x] Replace XML tag
    - [x] Replace ID in XML
    - [x] Replace ID in code
  - [x] Change type in code
    - [x] Change name of private variable from listview to recyclerView
    - [x] Modify adapter to suit new type
    - [x] Change setOnItemClickListener to correct listener
- [x] Switch from ListView to RecyclerView in ViewListActivity
  - [x] Replace XML tag
    - [x] Replace ID in XML
    - [x] Replace ID in code
  - [x] Change type in code
    - [x] Change name of private variable from listview to recyclerView
    - [x] Modify adapter to suit new type
